import Stripe from "stripe";

// Special accounts related to platform acct_1MZRIlLirQdaQn8E
const specialAccounts = [
  /*Standard CBSP:*/ "acct_1NBR5cQ55yzNh0Wh",
  /*Standard Non-CBSP:*/ "acct_1NTYufAm9SMRj986",
  /*Express:*/ "acct_1MhgrJPu4nAj1Tce",
  /*Custom:*/ "acct_1N9FIXQ26HdRlxHg",
  /*UA1:*/ "acct_1NUwRpPwYwgmBZjm",
  /*UA2:*/ "acct_1N61ByQ7NMZInEnp",
  /*UA3:*/ "acct_1NUwSMPxxtPxBTFe",
  /*UA7:*/ "acct_1NUwSoPqPnXR0qy5",
];

export const specialAccountsData: Record<string, Stripe.Account> = {
  "Standard CBSP": {
    id: "acct_1NBR5cQ55yzNh0Wh",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "Standard",
      support_address: {
        city: "Bothell",
        country: "US",
        line1: "16506 118th Ave NE",
        line2: null,
        postal_code: "98011",
        state: "WA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "+17625371622",
      support_url: "https://furever.dev",
      url: "gogole.com",
    },
    capabilities: {
      acss_debit_payments: "active",
      affirm_payments: "active",
      afterpay_clearpay_payments: "active",
      bancontact_payments: "active",
      card_payments: "active",
      cartes_bancaires_payments: "pending",
      cashapp_payments: "active",
      eps_payments: "active",
      giropay_payments: "active",
      ideal_payments: "active",
      klarna_payments: "active",
      link_payments: "active",
      p24_payments: "active",
      sepa_debit_payments: "active",
      sofort_payments: "active",
      transfers: "active",
      us_bank_account_ach_payments: "active",
    },
    charges_enabled: true,
    controller: {
      is_controller: true,
      type: "application",
    },
    country: "US",
    created: 1684970853,
    default_currency: "usd",
    details_submitted: true,
    email: "jorgea+test@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1NBR6XQ55yzNh0Wh8Q9pPRHk",
          object: "bank_account",
          account: "acct_1NBR5cQ55yzNh0Wh",
          account_holder_name: null,
          account_holder_type: null,
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
        {
          id: "ba_1NBR5cQ55yzNh0WhUWFSz41f",
          object: "bank_account",
          account: "acct_1NBR5cQ55yzNh0Wh",
          account_holder_name: "Jenny Rosen",
          account_holder_type: "individual",
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: false,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
      ],
      has_more: false,
      url: "/v1/accounts/acct_1NBR5cQ55yzNh0Wh/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    metadata: {},
    payouts_enabled: true,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: true,
          cvc_failure: true,
        },
        statement_descriptor_prefix: "34534WDSFS",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "Gogole",
        timezone: "Etc/UTC",
      },
      payouts: {
        debit_negative_balances: true,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: 1684970920,
    },
    type: "standard",
  } as any,
  "Standard Non-CBSP": {
    id: "acct_1NTYufAm9SMRj986",
    object: "account",
    business_profile: {
      mcc: "5734",
      name: "Standard Non-CBSP",
      support_address: {
        city: "New York",
        country: "US",
        line1: "118th Avenue",
        line2: null,
        postal_code: "11434",
        state: "NY",
      },
      support_email: null,
      support_phone: "+14257537115",
      support_url: null,
      url: "google.com",
    },
    capabilities: {
      acss_debit_payments: "inactive",
      affirm_payments: "inactive",
      afterpay_clearpay_payments: "inactive",
      bancontact_payments: "inactive",
      card_payments: "inactive",
      cartes_bancaires_payments: "inactive",
      cashapp_payments: "inactive",
      eps_payments: "inactive",
      giropay_payments: "inactive",
      ideal_payments: "inactive",
      klarna_payments: "inactive",
      link_payments: "inactive",
      p24_payments: "inactive",
      sepa_debit_payments: "inactive",
      sofort_payments: "inactive",
      transfers: "inactive",
      us_bank_account_ach_payments: "inactive",
    },
    charges_enabled: false,
    controller: {
      type: "account",
    },
    country: "US",
    default_currency: "usd",
    details_submitted: true,
    email: "jorgea+test@stripe.com",
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    metadata: {},
    payouts_enabled: false,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [
        "individual.verification.document",
        "individual.verification.proof_of_liveness",
      ],
      disabled_reason: "requirements.past_due",
      errors: [
        {
          code: "verification_failed_keyed_identity",
          reason:
            "The identity information you entered cannot be verified. Please correct any errors or upload a document that matches the identity fields (e.g., name and date of birth) that you entered.",
          requirement: "individual.verification.document",
        },
      ],
      eventually_due: [
        "individual.verification.document",
        "individual.verification.proof_of_liveness",
      ],
      past_due: [
        "individual.verification.document",
        "individual.verification.proof_of_liveness",
      ],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        statement_descriptor_prefix: "AZASD234",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "JorgeStandardAccount",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "GOOGLE.COM",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      sepa_debit_payments: {},
    },
    type: "standard",
  } as any,
  Express: {
    id: "acct_1MhgrJPu4nAj1Tce",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "Express",
      support_address: {
        city: "South San Francisco",
        country: null,
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "4257537116",
      support_url: "https://furever.dev",
      url: "https://furever.dev3",
    },
    capabilities: {
      card_payments: "active",
      transfers: "active",
    },
    charges_enabled: true,
    country: "US",
    created: 1677881630,
    default_currency: "usd",
    details_submitted: true,
    email: "jorgea+express@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1NJgekPu4nAj1Tce00WZhzHj",
          object: "bank_account",
          account: "acct_1MhgrJPu4nAj1Tce",
          account_holder_name: null,
          account_holder_type: null,
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
        {
          id: "card_1NXtEFPu4nAj1TceXiPadpQY",
          object: "card",
          account: "acct_1MhgrJPu4nAj1Tce",
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          available_payout_methods: ["standard", "instant"],
          brand: "Visa",
          country: "US",
          currency: "usd",
          cvc_check: null,
          default_for_currency: false,
          dynamic_last4: null,
          exp_month: 7,
          exp_year: 2024,
          fingerprint: "oscHdFZS8lKyaZ8d",
          funding: "debit",
          last4: "5556",
          metadata: {},
          name: null,
          status: "new",
          tokenization_method: null,
          wallet: null,
        },
      ],
      has_more: false,
      total_count: 2,
      url: "/v1/accounts/acct_1MhgrJPu4nAj1Tce/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    login_links: {
      object: "list",
      data: [],
      has_more: false,
      total_count: 0,
      url: "/v1/accounts/acct_1MhgrJPu4nAj1Tce/login_links",
    },
    metadata: {},
    payouts_enabled: true,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: false,
          cvc_failure: false,
        },
        statement_descriptor_prefix: "FUREVER",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "Test, Inc",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "FUREVER",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      payouts: {
        debit_negative_balances: true,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: 1685569182,
    },
    type: "express",
  } as any,
  Custom: {
    id: "acct_1N9FIXQ26HdRlxHg",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "Custom",
      product_description: "Description",
      support_address: {
        city: "South San Francisco",
        country: null,
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "4257537116",
      support_url: "https://furever.dev",
      url: "https://furever.dev",
    },
    business_type: "individual",
    capabilities: {
      card_payments: "active",
      transfers: "active",
    },
    charges_enabled: true,
    company: {
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      directors_provided: true,
      executives_provided: true,
      name: null,
      owners_provided: true,
      phone: "+14257537115",
      tax_id_provided: false,
      verification: {
        document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
      },
    },
    country: "US",
    created: 1684448870,
    default_currency: "usd",
    details_submitted: true,
    email: "jorgea@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1N9FIXQ26HdRlxHgCWf8aeN7",
          object: "bank_account",
          account: "acct_1N9FIXQ26HdRlxHg",
          account_holder_name: "Jenny Rosen",
          account_holder_type: "individual",
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/accounts/acct_1N9FIXQ26HdRlxHg/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    individual: {
      id: "person_1N9FIYQ26HdRlxHgBWsQ5T4j",
      object: "person",
      account: "acct_1N9FIXQ26HdRlxHg",
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      created: 1684448870,
      dob: {
        day: 1,
        month: 1,
        year: 1990,
      },
      email: "jenny.rosen@example.com",
      first_name: "Jenny",
      future_requirements: {
        alternatives: [],
        currently_due: [],
        errors: [],
        eventually_due: [],
        past_due: [],
        pending_verification: [],
      },
      id_number_provided: true,
      last_name: "Rosen",
      metadata: {},
      phone: "+14257537115",
      relationship: {
        director: false,
        executive: false,
        owner: false,
        percent_ownership: null,
        representative: true,
        title: null,
      },
      requirements: {
        alternatives: [],
        currently_due: [],
        errors: [],
        eventually_due: [],
        past_due: [],
        pending_verification: [],
      },
      ssn_last_4_provided: true,
      verification: {
        additional_document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
        details: null,
        details_code: null,
        document: {
          back: null,
          details: null,
          details_code: null,
          front: "file_1NAd9dGYmfBHZbWK4tfvgmRf",
        },
        status: "verified",
      },
    },
    metadata: {},
    payouts_enabled: true,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: false,
          cvc_failure: false,
        },
        statement_descriptor_prefix: "FUREVER",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "furever.dev",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "FUREVER",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      payouts: {
        debit_negative_balances: false,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: 1684778906,
      ip: "50.47.231.6",
      user_agent:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    },
    type: "custom",
  } as any,
  UA1: {
    id: "acct_1NUwRpPwYwgmBZjm",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "UA1",
      product_description: "Description",
      support_address: {
        city: "South San Francisco",
        country: null,
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "4257537116",
      support_url: "https://furever.dev",
      url: "https://furever.dev",
    },
    business_type: "individual",
    capabilities: {},
    charges_enabled: false,
    company: {
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      directors_provided: true,
      executives_provided: true,
      name: null,
      owners_provided: true,
      phone: "+14257537115",
      tax_id_provided: false,
      verification: {
        document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
      },
    },
    controller: {
      is_controller: true,
      type: "application",
    },
    country: "US",
    created: 1689619626,
    default_currency: "usd",
    details_submitted: false,
    email: "jorgea@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1NUwRpPwYwgmBZjm8oQ7QJ6h",
          object: "bank_account",
          account: "acct_1NUwRpPwYwgmBZjm",
          account_holder_name: "Jenny Rosen",
          account_holder_type: "individual",
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/accounts/acct_1NUwRpPwYwgmBZjm/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    individual: {
      id: "person_1NUwRqPwYwgmBZjmNF6aP6mb",
      object: "person",
      account: "acct_1NUwRpPwYwgmBZjm",
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      created: 1689619626,
      dob: {
        day: 1,
        month: 1,
        year: 1901,
      },
      email: "jenny.rosen@example.com",
      first_name: "Jenny",
      future_requirements: {
        alternatives: [],
        currently_due: [],
        errors: [],
        eventually_due: [],
        past_due: [],
        pending_verification: [],
      },
      id_number_provided: false,
      last_name: "Rosen",
      metadata: {},
      phone: "+14257537115",
      relationship: {
        director: false,
        executive: false,
        owner: false,
        percent_ownership: null,
        representative: true,
        title: null,
      },
      requirements: {
        alternatives: [],
        currently_due: [],
        errors: [],
        eventually_due: [],
        past_due: [],
        pending_verification: [],
      },
      ssn_last_4_provided: true,
      verification: {
        additional_document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
        details: null,
        details_code: null,
        document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
        status: "pending",
      },
    },
    metadata: {},
    payouts_enabled: false,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      disabled_reason: "requirements.past_due",
      errors: [],
      eventually_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      past_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: true,
          cvc_failure: true,
        },
        statement_descriptor_prefix: "FUREVER",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "furever.dev",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "FUREVER",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      payouts: {
        debit_negative_balances: true,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: null,
      ip: null,
      user_agent: null,
    },
    type: "standard",
  } as any,
  UA2: {
    id: "acct_1N61ByQ7NMZInEnp",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "UA2",
      support_address: {
        city: "Bothell",
        country: "US",
        line1: "16506 118th Ave NE",
        line2: null,
        postal_code: "98011",
        state: "WA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "+17625371622",
      support_url: "https://furever.dev",
      url: "gogole.com",
    },
    capabilities: {
      acss_debit_payments: "inactive",
      affirm_payments: "inactive",
      afterpay_clearpay_payments: "inactive",
      bancontact_payments: "inactive",
      card_payments: "inactive",
      cartes_bancaires_payments: "inactive",
      eps_payments: "inactive",
      giropay_payments: "inactive",
      ideal_payments: "inactive",
      klarna_payments: "inactive",
      link_payments: "inactive",
      p24_payments: "inactive",
      sepa_debit_payments: "inactive",
      sofort_payments: "inactive",
      transfers: "inactive",
      us_bank_account_ach_payments: "inactive",
    },
    charges_enabled: false,
    controller: {
      is_controller: true,
      type: "application",
    },
    country: "US",
    created: 1683679663,
    default_currency: "usd",
    details_submitted: false,
    email: "jorgea+test@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1N73nyQ7NMZInEnpVnuVp7hN",
          object: "bank_account",
          account: "acct_1N61ByQ7NMZInEnp",
          account_holder_name: null,
          account_holder_type: null,
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
        {
          id: "ba_1N61ByQ7NMZInEnp4ka6rIKs",
          object: "bank_account",
          account: "acct_1N61ByQ7NMZInEnp",
          account_holder_name: "Jenny Rosen",
          account_holder_type: "individual",
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: false,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
      ],
      has_more: false,
      total_count: 2,
      url: "/v1/accounts/acct_1N61ByQ7NMZInEnp/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    metadata: {},
    payouts_enabled: false,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      disabled_reason: "requirements.past_due",
      errors: [],
      eventually_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      past_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: true,
          cvc_failure: true,
        },
        statement_descriptor_prefix: "34534WDSFS",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "Gogole",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "GOGOLE.COM",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      payouts: {
        debit_negative_balances: true,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: null,
    },
    type: "standard",
  } as any,
  UA3: {
    id: "acct_1NUwSMPxxtPxBTFe",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "UA3",
      product_description: "Description",
      support_address: {
        city: "South San Francisco",
        country: null,
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "4257537116",
      support_url: "https://furever.dev",
      url: "https://furever.dev",
    },
    business_type: "individual",
    capabilities: {
      card_payments: "inactive",
      transfers: "inactive",
    },
    charges_enabled: false,
    company: {
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      directors_provided: true,
      executives_provided: true,
      name: null,
      owners_provided: true,
      phone: "+14257537115",
      tax_id_provided: false,
      verification: {
        document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
      },
    },
    controller: {
      is_controller: true,
      type: "application",
    },
    country: "US",
    created: 1689619659,
    default_currency: "usd",
    details_submitted: false,
    email: "jorgea@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1NUwSMPxxtPxBTFeEPzhlcra",
          object: "bank_account",
          account: "acct_1NUwSMPxxtPxBTFe",
          account_holder_name: "Jenny Rosen",
          account_holder_type: "individual",
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/accounts/acct_1NUwSMPxxtPxBTFe/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    individual: {
      id: "person_1NUwSMPxxtPxBTFe8ILqr1BX",
      object: "person",
      account: "acct_1NUwSMPxxtPxBTFe",
      address: {
        city: "South San Francisco",
        country: "US",
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      created: 1689619659,
      dob: {
        day: 1,
        month: 1,
        year: 1901,
      },
      email: "jenny.rosen@example.com",
      first_name: "Jenny",
      future_requirements: {
        alternatives: [],
        currently_due: [],
        errors: [],
        eventually_due: [],
        past_due: [],
        pending_verification: [],
      },
      id_number_provided: true,
      last_name: "Rosen",
      metadata: {},
      phone: "+14257537115",
      relationship: {
        director: false,
        executive: false,
        owner: false,
        percent_ownership: null,
        representative: true,
        title: null,
      },
      requirements: {
        alternatives: [],
        currently_due: [],
        errors: [],
        eventually_due: [],
        past_due: [],
        pending_verification: [],
      },
      ssn_last_4_provided: true,
      verification: {
        additional_document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
        details: null,
        details_code: null,
        document: {
          back: null,
          details: null,
          details_code: null,
          front: null,
        },
        status: "verified",
      },
    },
    metadata: {},
    payouts_enabled: false,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      disabled_reason: "requirements.past_due",
      errors: [],
      eventually_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      past_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: false,
          cvc_failure: false,
        },
        statement_descriptor_prefix: "FUREVER",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "furever.dev",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "FUREVER",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      payouts: {
        debit_negative_balances: false,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: null,
      ip: null,
      user_agent: null,
    },
    type: "standard",
  } as any,
  UA7: {
    id: "acct_1NUwSoPqPnXR0qy5",
    object: "account",
    business_profile: {
      mcc: "7299",
      name: "UA7",
      support_address: {
        city: "South San Francisco",
        country: null,
        line1: "354 Oyster Point Blvd",
        line2: null,
        postal_code: "94080",
        state: "CA",
      },
      support_email: "jorgea@stripe.com",
      support_phone: "4257537116",
      support_url: "https://furever.dev",
      url: "https://furever.dev",
    },
    capabilities: {
      card_payments: "inactive",
      transfers: "inactive",
    },
    charges_enabled: false,
    controller: {
      is_controller: true,
      type: "application",
    },
    country: "US",
    created: 1689619687,
    default_currency: "usd",
    details_submitted: false,
    email: "jorgea@stripe.com",
    external_accounts: {
      object: "list",
      data: [
        {
          id: "ba_1NUwSoPqPnXR0qy5dOYxnDrs",
          object: "bank_account",
          account: "acct_1NUwSoPqPnXR0qy5",
          account_holder_name: "Jenny Rosen",
          account_holder_type: "individual",
          account_type: null,
          available_payout_methods: ["standard"],
          bank_name: "STRIPE TEST BANK",
          country: "US",
          currency: "usd",
          default_for_currency: true,
          fingerprint: "kXBJvrtN1KPfMQlM",
          future_requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          last4: "6789",
          metadata: {},
          requirements: {
            currently_due: [],
            errors: [],
            past_due: [],
            pending_verification: [],
          },
          routing_number: "110000000",
          status: "new",
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/accounts/acct_1NUwSoPqPnXR0qy5/external_accounts",
    },
    future_requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: [],
      disabled_reason: null,
      errors: [],
      eventually_due: [],
      past_due: [],
      pending_verification: [],
    },
    metadata: {},
    payouts_enabled: false,
    requirements: {
      alternatives: [],
      current_deadline: null,
      currently_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      disabled_reason: "requirements.past_due",
      errors: [],
      eventually_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      past_due: ["tos_acceptance.date", "tos_acceptance.ip"],
      pending_verification: [],
    },
    settings: {
      bacs_debit_payments: {},
      branding: {
        icon: null,
        logo: null,
        primary_color: null,
        secondary_color: null,
      },
      card_issuing: {
        tos_acceptance: {
          date: null,
          ip: null,
        },
      },
      card_payments: {
        decline_on: {
          avs_failure: false,
          cvc_failure: false,
        },
        statement_descriptor_prefix: "FUREVER",
        statement_descriptor_prefix_kana: null,
        statement_descriptor_prefix_kanji: null,
      },
      dashboard: {
        display_name: "furever.dev",
        timezone: "Etc/UTC",
      },
      payments: {
        statement_descriptor: "FUREVER",
        statement_descriptor_kana: null,
        statement_descriptor_kanji: null,
      },
      payouts: {
        debit_negative_balances: true,
        schedule: {
          delay_days: 2,
          interval: "daily",
        },
        statement_descriptor: null,
      },
      sepa_debit_payments: {},
    },
    tos_acceptance: {
      date: null,
    },
    type: "standard",
  } as any,
};
