import { initializeIcons } from '@fluentui/react';
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react';
import { App } from '../components/App';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <App />
    </div>
  )
}

// Only run in client
if (typeof window !== 'undefined') {
  initializeIcons()
}

export default Home
